Update filter options and fix bugs in item details selection
GangeiKan510/onlyfrogs-stylesync-client-v2 pull request #70
Opened 2024-11-14 06:32 UTC by jaycellearianne

https://github.com/user-attachments/assets/c10c486a-1204-4c07-a628-6a23681aaa4a

2024-11-14 15:05 UTC, Dave00913 approved these changes

2024-11-15 10:52 UTC, GangeiKan510 commented on components/home/pieces/PiecesTab.tsx
> +  const getColorHexCode = (colorName: string): string | undefined => {
pwede ka ka himo utility function yan then transfer mo sa `utils` directory ta. Medjo ga damo na ang lines ta sa amo ni nga file basi di na maintain kag budlay na ichange later on

2024-11-15 10:52 UTC, GangeiKan510 commented on components/home/pieces/PiecesTab.tsx
> +  const filterOptions = () => {
same man diri

2024-11-15 10:54 UTC, GangeiKan510 requested changes

2024-11-15 10:54 UTC, GangeiKan510 commented on components/home/pieces/PiecesTab.tsx
> +// import { categoryTypes } from "@/components/constants/clothing-details/categories";
unused na ni and gin comment out?

2024-11-16 08:26 UTC, GangeiKan510 approved these changes

2024-11-16 08:26 UTC, GangeiKan510 commented on components/home/pieces/PiecesTab.tsx
> +      item.season?.forEach((s) => filterOptions.season.add(s));
please change to word gid like `season` instead of `s` lang

2024-11-16 09:26 UTC, merged